# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kuKeGytQsEM9-t0yGsojGWjCocX4u-OQ
"""

import numpy as np
import pandas as pd

import requests
from bs4 import BeautifulSoup

URL = 'https://timely-sunshine-e821b3.netlify.app/'

page = requests.get(URL)

page.status_code

htmlCode = page.text
soup = BeautifulSoup(htmlCode)

htmlCode

content = soup.find('div', attrs={'class' : 'main'})
text = content.text
# print(text)

r1 = text.split("\n")
#print(r1)
r2 = []
for i in r1:
  if i != '' and i!='\r':
    r2.append(i)
#print(r2)
r3 = []
for i in r2:
  k = i.strip()
  r3.append(k)
#print(r3)
r4 = []
for i in r3:
  if i!='':
    r4.append(i)
print(r4)
names = []
price = []
for i in range(0,len(r4),2):
  names.append(r4[i])
  price.append(r4[i+1])
print(names)
print(price)

df = pd.DataFrame({'Product_Names':names,'MRP' : price})
df

df.to_csv('products.csv', header = True, index = False)

from google.colab import files
files.download('products.csv')